export const REQUESTED_USERS = 'REQUESTED_USERS';
export const REQUESTED_USERS_FAILED = 'REQUESTED_USERS_FAILED';
export const REQUESTED_USERS_SUCCESS = 'REQUESTED_USERS_SUCCESS';
export const FETCH_USERS = 'FETCH_USERS';

export const REQUESTED_USER = 'REQUESTED_USER';
export const REQUESTED_USER_FAILED = 'REQUESTED_USER_FAILED';
export const REQUESTED_USER_SUCCESS = 'REQUESTED_USER_SUCCESS';
export const FETCH_USER = 'FETCH_USER';

export const REQUESTED_USER_ALBUMS = 'REQUESTED_USER_ALBUMS';
export const REQUESTED_USER_ALBUMS_FAILED = 'REQUESTED_USER_ALBUMS_FAILED';
export const REQUESTED_USER_ALBUMS_SUCCESS = 'REQUESTED_USER_ALBUMS_SUCCESS';
export const FETCH_USER_ALBUMS = 'FETCH_USER_ALBUMS';

export const REQUESTED_ALBUMS = 'REQUESTED_ALBUMS';
export const REQUESTED_ALBUMS_FAILED = 'REQUESTED_ALBUMS_FAILED';
export const REQUESTED_ALBUMS_SUCCESS = 'REQUESTED_ALBUMS_SUCCESS';
export const FETCH_ALBUMS = 'FETCH_ALBUMS';

