export const REQUESTED_USERS = 'REQUESTED_USERS';
export const REQUESTED_USERS_FAILED = 'REQUESTED_USERS_FAILED';
export const REQUESTED_USERS_SUCCESS = 'REQUESTED_USERS_SUCCESS';
export const FETCH_USERS = 'FETCH_USERS';
